### ISSUE TITLE
Please increase max PVC count for dqszvc-dev to 60.

### ISSUE THREAD

**Issue by poggdogg** [BCDevOps/devops-requests#287]
## Step 0
**Are you the product owner or technical lead?**
Yes

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What quotas need to be changed? (Select all that apply)
- [\] Storage: Netapp Block (storage-netapp-block-standard-quota)

## Step 3
Add details about your quota request here:
Please increase the number of PVCs that can be provisioned to 60 for *dqszvc-dev*.  I will reduce the size to 1/4 GB ea.

## Step 4
Please explain here the reasons for requesting your quota change.
Remember that OCP is a shared resource. Please be community-minded in making these requests and include thorough details about why your project's current resource usage cannot be reduced to adhere to the existing quota requirements.

Discussed at length in RocketChat with @caggles ; we have a PR-based pipeline and recently added a second database to the pipeline.

**Comment by jefkel** [comment]
@poggdogg Can you give a bit more detail on what didn't work with using ephemeral storage for your dev DB's?  (I have used ephemeral DB's with no issues, and would like to know what issue you're running into that's blocking your use there.)

**Comment by poggdogg** [comment]
We were getting alot of 'Unexpected EOF' when standing up the databases in deployments.  This was a couple of months ago.

**Comment by jefkel** [comment]
do you have a link to the manifest you used that had that issue?  I'd like to do a quick test (I have a couple of ideas on what may have contributed to that issue that I'd like to prove out)

**Comment by poggdogg** [comment]
No, I don't.  
This is currently halting our CI/CD pipeline and retooling will slow us down further.
I've reduced our claim sizes from 1GB to 256MB in the newer branches and could reduce again if needed.  Are there any other reasons why we can't get this queue increased?

**Comment by jefkel** [comment]
Looks like you'll need to modify your current deployments.  I would suggest starting with your database backends:
- adding a section in your spec to enable anti-affinity
  - suggest creating a "database" label or something that could be common to all your DB's to push your databases to different nodes
- modify your storage to leverage EmptyDir

These 2 settings should correct both your current quota consumption issue as well as the occasional issue you were previously running into re: 'Unexpected EOF'

Sample Yaml to add to your db deployments:
``` yaml
    metadata:
      labels:
        dev-app: database
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: dev-app
                operator: In
                values:
                - database
            topologyKey: "kubernetes.io/hostname"
```
